cart/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^remove/(?P<product_id>\d+)/(?P<size>.*)/$', views.cart_remove, name='remove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^ordering/$', views.ordering, name='ordering'),
]

menu/urls.py
from django.conf.urls import url
from menu import views


urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^shop/(?P<slug>.*)/category/$', views.items_list, name='items_list'),
]

miltec/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('menu.urls', namespace='menu')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^buyer/', include('buyer.urls', namespace='buyer')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django import forms
from buyer.forms import BuyerRegisterForm


class SelectWidget(forms.Select):
    class Media:
        css = {
            'all': ('css/cart_select.css',)
        }


class CartAddProductForm(forms.Form):

    quantity = forms.TypedChoiceField(label='Количество', label_suffix='',
                                      widget=SelectWidget, coerce=int)
    size = forms.TypedChoiceField(label='Размер', label_suffix='', required=False,
                                  widget=SelectWidget)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class SendMassageForm(BuyerRegisterForm):

    address = forms.CharField(label='Адрес новой почти',
                              widget=forms.TextInput(attrs={'placeholder': 'выбирите адрес отделения новой почты'}),
                              help_text='Відділення №7 вулиця Корольова, 15А, Рівне, Рівненська область')

    cart_email = forms.EmailField(label='E-mail',
                                  required=False, widget=forms.EmailInput(attrs={'placeholder': 'E-Mail',
                                                                                 'id': 'userid',
                                                                                 'name': 'userid',
                                                                                 'title': 'E-Mail'}))
    password1 = None
    password2 = None
    sex = None

    class Meta(BuyerRegisterForm.Meta):
        exclude = ['date_of_birth', 'sex', 'password', 'email']

cart/views.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from .cart import Cart
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.template.loader import render_to_string
from cart.forms import SendMassageForm
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.contrib import messages
from email.mime.image import MIMEImage


def django_message(request, template, data, name_value):
    message = messages.get_messages(request)
    if message:
        data[name_value] = render_to_string(template,
                                            {'messages': message},
                                            request=request)


@require_POST
def cart_add(request, product_id):
    if request.is_ajax():
        data = dict()
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = product.get_cart_form(request_form=request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product, quantity=cd['quantity'],
                     size=cd['size'], update_quantity=cd['update'])

            data['form_valid'] = True
            data['total_price'] = cart.get_total_price()
            messages.success(request, "Вы добавили в корзину '{}'.".format(product.title), extra_tags='success')
        else:
            data['form_valid'] = False

        django_message(request, 'messages.html', data, 'html_messages')

        return JsonResponse(data)
    else:
        return redirect(reverse('menu:shop'))


def cart_remove(request, product_id, size):
    if request.is_ajax():
        data = dict()
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product, size)

        data['total_price'] = cart.get_total_price()
        if not cart.get_total_price():
            data['empty_cart'] = render_to_string('empty_cart.html', request=request)

        return JsonResponse(data)

    return redirect('cart:detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart_detail.html', {'cart': cart})


def ordering(request):
    cart = Cart(request)
    if cart:
        if request.user.is_authenticated():
            massage_form = SendMassageForm(initial={'cart_email': request.user.email,
                                                    'first_name': request.user.first_name,
                                                    'last_name': request.user.last_name,
                                                    'phone_number': request.user.phone_number})
        else:
            massage_form = SendMassageForm()

        if request.POST:
            massage_form = SendMassageForm(request.POST)
            if massage_form.is_valid():
                cart_email = massage_form.cleaned_data['cart_email']
                first_name = massage_form.cleaned_data['first_name']
                last_name = massage_form.cleaned_data['last_name']
                phone_number = massage_form.cleaned_data['phone_number']
                address = massage_form.cleaned_data['address']

                subject = "{} {}".format(first_name.title(), last_name.title())
                from_email = settings.EMAIL_HOST_USER
                to_email = [settings.EMAIL_HOST_USER, 'mishaelitzem2@rambler.ru', 'brute_force@ukr.net']

                context = {'buyer': subject,
                           'phone_number': phone_number,
                           'address': address,
                           'cart': cart}

                if cart_email:
                    context['cart_email'] = cart_email

                html_message = render_to_string('send_ordering.html', context, request=request).strip()

                msg = EmailMultiAlternatives(subject, html_message,  from_email, to_email)
                msg.content_subtype = 'html'
                msg.mixed_subtype = 'related'

                for item in cart:
                    # Create an inline attachment
                    image = MIMEImage(item['product'].image.read())
                    image.add_header('Content-ID', '<{}>'.format(item['product'].article))
                    msg.attach(image)

                msg.send()
                del request.session['cart']

                messages.success(request, 'Заказ офомлен успешно. Ждите нашего звонка!', extra_tags='success')
                return redirect('menu:homepage')

        context = {'form': massage_form,
                   'cart': cart}

        return render(request, 'cart_ordering.html', context)
    else:
        return redirect('menu:shop')

cart/templates/cart/cart_detail.html
{% extends "base.html" %}{% load staticfiles %}


{% block title %}
    Ваша корзина товаров
{% endblock %}

{% block script %}
    <link href="{% static 'css/cart.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/cart.js' %}"></script>
{% endblock %}

{% block cart %}

    <div id="cart-details" class="my-shop" style="margin-bottom: 15em;">

        {% if cart %}

            <div class="form-title">
                <h3>Ваша корзина товаров</h3>
            </div>

            <table class="cart">
                <thead>
                <tr>
                    <th>Изображение</th>
                    <th>Продукт</th>
                    <th>Количество</th>
                    <th>Размер</th>
                    <th>Удалить</th>
                    <th>Полная цена</th>
                    <th>Цена</th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr id="cart-product-{{ product.id }}-{{ item.size }}">
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}" alt="" style="max-height: 5rem"/>
                                </a>
                            </td>
                            <td>
                                <p>{{ product.title }}</p>
                            </td>
                            <td>
                                <p>{{ item.quantity }}</p>
                            </td>

                            {% if  item.size %}
                                <td>
                                    <p>{{ item.size }}</p>
                                </td>
                            {% else %}
                                <td>
                                    <p>-</p>
                                </td>
                            {% endif %}

                            <td>
                                <p class="remove-link">
                                    <a class="cart-remove" href="{% url "cart:remove" product.id item.size %}" data-product="cart-product-{{ product.id }}-{{ item.size }}">Удалить</a>
                                </p>
                            </td>
                            <td class="num">
                                <p>{{ item.price }} EUR*</p>
                            </td>
                            <td class="num">
                                <p>{{ item.total_price }} EUR*</p>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>
                        <p>Всего</p>
                    </td>
                    <td colspan="5"></td>
                    <td id="total_price" class="num">
                        <p>{{ cart.get_total_price }} EUR*</p>
                    </td>
                </tr>
                </tbody>
            </table>

            <div class="clearfix cart-total">
         <span class="cart-return-link">
             <span class="btn-link btn-link-gray">
                 <a href="{% url "menu:shop"%}" class="btn-link-i" name="close">ПРОДОЛЖИТЬ ШОПИНГ</a>
             </span>
         </span>
         <span class="cart-submit">
             <span class="btn-link-green btn-link">
                  <a href="{% url 'cart:ordering' %}" class="btn-link-i" name="close">ОФОРМИТЬ ЗАКАЗ</a>
             </span>
         </span>
            </div>

        {% else %}

            {% include "empty_cart.html" %}

        {% endif %}

    </div>

{% endblock cart %}

cart/templates/cart/cart_form.html


<form class="cart-form" action="{% url "cart:add" product.id %}" method="post">
    {% csrf_token %}

    {% with form=product.get_cart_form %}
        {{ form.non_field_errors }}

        {{ form.quantity.errors }}
        {{ form.quantity.label_tag }}
        {{ form.quantity }}

        {% if product.get_sizes %}
            {{ form.size.errors }}
            {{ form.size.label_tag }}
            {{ form.size }}
        {% endif %}

        {{ form.update.errors }}
        {{ form.update }}

    {% endwith %}

    <div class="clearfix cart-total">
         <span class="cart-submit">
             <span class="btn-link-green btn-link">
                 <button class="btn-link-i" id="popup-checkout" type="submit">Добавить в корзину</button>
             </span>
         </span>
    </div>
</form>

cart/templates/cart/cart_ordering.html
{% extends "base.html" %}{% load staticfiles %}


{% block title %}
    Оформление заказа
{% endblock %}

{% block script %}

    <link href="{% static 'css/cart.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/cart.js' %}"></script>

    <script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyCCGuxN6OjpeVdH6rFh2AABSTV_-ahgr9U&libraries=places'></script>
    <script src="{% static 'js/google_geolocation.js' %}" type="text/javascript"></script>

    <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css">

{% endblock %}


{% block cart %}

    <div class="boxen">

        <div id="ordering" class="my-shop box" style="margin-bottom: 15em;">

            <div class="forms">

                <div class="form-title">
                    <h3>Оформление заказа</h3>
                </div>

                <form class="register yform" method="post" action="">

                    {% csrf_token %}

                    {% for field in form %}

                        {% if field.errors %}
                            <div class="form-group has-error">

                                {% for error in field.errors %}

                                    <label class="control-label errorlist">
                                        <em>{{ error }}</em>
                                    </label>

                                {% endfor %}

                            </div>
                        {% endif %}

                        <div class="type-text">

                            {{ field.label_tag }}

                            {{ field }}

                            {% if field.help_text %}
                                <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}

                        </div>

                    {% endfor %}

                    <div class="clearfix cart-total">
                         <span class="cart-return-link">
                             <span class="btn-link btn-link-gray">
                                 <a href="{% url 'menu:homepage' %}" class="btn-link-i" name="close">ВЕРНУТЬСЯ НАЗАД</a>
                             </span>
                         </span>
                        <span class="cart-submit">
                             <span class="btn-link-green btn-link">
                                 <button class="btn-link-i" id="popup-checkout" type="submit">ОТПРАВИТЬ</button>
                             </span>
                         </span>
                    </div>
                </form>

            </div>

            <div id="ordering-list">
                <div class="widget" role="actions">

                    <h2>Список товаров</h2>

                    <div class="cart-ordering">

                        <table class="cart">
                            <tbody>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr id="cart-product-{{ product.id }}-{{ item.size }}">
                                        <td>
                                            <a href="{{ product.get_absolute_url }}">
                                                <img src="{{ product.image.url }}" alt="{{ product.title }}"/>
                                            </a>
                                        </td>
                                        <td>{{ product.title }}</td>
                                        <td>{{ item.quantity }}шт.</td>
                                        <td class="num">{{ item.total_price }} EUR*</td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                            <tr class="total">
                                <td colspan="2">Всего</td>
                                <td colspan="2" id="total_price" class="num">{{ cart.get_total_price }} EUR*</td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <div class="aligned-center">
                                        <a class="check-edit-order-link"  href="{% url 'cart:detail' %}" name="edit" >
                                            Редактировать заказ
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>

                    </div>

                    <div class="widgetBottom"></div>
                </div>
            </div>

        </div>

        <div id="map" class="my-shop box" hidden="hidden"></div>

    </div>

    {#    <link rel='stylesheet' href='https://apimgmtstorelinmtekiynqw.blob.core.windows.net/content/MediaLibrary/Widget/Map/styles/map.css' />#}
    {#    <div id="np-map"> <button type="button" id="npw-map-open-button">НАЙБЛИЖЧЕ ВІДДІЛЕННЯ</button> <script async="" defer="" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAPhm7Q29X5ldwjLtA7IMYHU_0xATiWK3A"></script> </div>#}
    {#    <script type='text/javascript' src='https://apimgmtstorelinmtekiynqw.blob.core.windows.net/content/MediaLibrary/Widget/Map/dist/map.min.js'></script>#}

{% endblock %}

cart/templates/cart/empty_cart.html
{% load staticfiles %}

<div class="empty-cart">
    <div class="form-title">
        <h3>Ваша корзина товаров пуста!</h3>
    </div>

    <div class="clearfix cart-total">
        <span class="cart-return-link">
             <span class="btn-link btn-link-gray">
                 <a href="{% url "menu:shop"%}" class="btn-link-i" name="close">ВЕРНУТЬСЯ В МАГАЗИН</a>
             </span>
        </span>
    </div>
</div>

cart/templates/cart/send_ordering.html

<div id="cart-details" class="my-shop" style="margin-bottom: 2em;">

    <style>
        table.cart {
            color: #000000;
            width: 97%;
            text-align: center;
            text-shadow: 0 0 1px #acacac,
            -1px -1px 0 hsl(0, 0%, 33%),
            -2px -2px 1px hsl(0, 0%, 0%),
            -2px -2px 2px hsl(0, 100%, 26%);
        }

        table.cart th {
            color: #000000;
            border: 2px #800 solid;
        }

        .cart tbody td {
            border: 2px #000000 solid;
        }

        .cart tbody tr.total td {
            font-size: 115%;
            border: 2px #800 solid;
            font-weight: bold;
        }

        table.cart td a {
            color: #880000;
            font-style: italic;
            text-decoration: none;
        }

        table.cart td p {
            background-color: rgba(0, 0, 0, 0.43);
            border-radius: 2px;
            padding: 2px 2px;
            box-shadow: 0 0 7px 4px rgba(195, 195, 195, 0.55);
            margin: 0;

        }

        table.cart td p a {
            border-bottom: 1px dotted;
        }

        table.cart img {
            border-radius: 0.3em;
            box-shadow: 0 0 7px 4px rgba(195, 195, 195, 0.55);
        }

    </style>

    <p><strong>Покупатель: </strong>{{ buyer }}</p>
    <p><strong>Номер телефона: </strong>{{ phone_number }}</p>
    <p><strong>Адрес Новой почти: </strong>{{ address }}</p>

    {% if cart_email %}
        <p><strong>E-mail: </strong>{{ cart_email }}</p>
    {% endif %}

    <div class="form-title" style="text-align: center">
        <h3>Заказ от {{ buyer }}</h3>
    </div>

    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Размер</th>
            <th>Полная цена</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr id="cart-product-{{ product.id }}-{{ item.size }}">
                    <td>
                        <a>
                            <img src="cid:{{ product.article }}" alt="" style="max-height: 5rem"/>
                        </a>
                    </td>
                    <td style="text-align: left">
                        <p>{{ product.title }}</p>
                    </td>
                    <td>
                        <p>{{ item.quantity }}</p>
                    </td>

                    {% if  item.size %}
                        <td>
                            <p>{{ item.size }}</p>
                        </td>
                    {% else %}
                        <td>
                            <p>-</p>
                        </td>
                    {% endif %}

                    <td class="num">
                        <p>{{ item.price }} EUR*</p>
                    </td>
                    <td class="num">
                        <p>{{ item.total_price }} EUR*</p>
                    </td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td colspan="2"></td>
            <td colspan="2">
                <p>Стоимость всего:</p>
            </td>
            <td colspan="2" id="total_price" class="num">
                <p>{{ cart.get_total_price }} EUR*</p>
            </td>
        </tr>
        </tbody>
    </table>
</div>