buyer/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'password_reset_form.html',
                                                          'email_template_name': 'password_reset_email.html',
                                                          'html_email_template_name': 'password_reset_email.html',
                                                          'subject_template_name': 'password_reset_subject.txt',
                                                          'post_reset_redirect': 'buyer:password_reset_done'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'password_reset_done.html',
                                                                    'current_app': 'buyer'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name': 'password_reset_confirm.html',
         'post_reset_redirect': 'buyer:password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^update/$', views.update, name='update'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^logout/$', views.logout, name='logout'),
    ]


cart/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^remove/(?P<product_id>\d+)/(?P<size>.*)/$', views.cart_remove, name='remove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^ordering/$', views.ordering, name='ordering'),
]

menu/urls.py
from django.conf.urls import url
from menu import views


urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^shop/(?P<slug>.*)/category/$', views.items_list, name='items_list'),
]

miltec/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('menu.urls', namespace='menu')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^buyer/', include('buyer.urls', namespace='buyer')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyer/models.py
# -*- encoding: utf-8 -*-
"""
This module create custom buyer-user.
"""

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
# from django_phonenumbers.model.fields import PhoneNumberField
from phonenumber_field.modelfields import PhoneNumberField
from address.models import AddressField


class MyUserManager(BaseUserManager):

    def create_user(self, email, first_name, last_name, date_of_birth, sex, address, phone_number, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Профиль должен иметь электронный адрес')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            date_of_birth=date_of_birth,
            address=address,
            phone_number=phone_number,
            sex=sex
            )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, first_name,  last_name,
                         address, phone_number, sex):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            address=address,
            phone_number=phone_number,
            sex=sex
        )
        user.set_password(password)
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class BuyerUser(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(
        verbose_name='Электронный адрес',
        max_length=255,
        unique=True,
        )

    first_name = models.CharField('Имя', max_length=25)
    last_name = models.CharField('Фамилия', max_length=25)
    date_of_birth = models.DateField(blank=True, null=True, verbose_name="Дата рождения")
    sex = models.CharField(max_length=20, choices=(('Man', 'Мужчина'), ('Woman', 'Женщина')),
                           verbose_name="Стать")

    address = AddressField(verbose_name="Адрес", max_length=500)
    phone_number = PhoneNumberField(verbose_name='Телефонный номер')

    profile_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания профиля")
    profile_update = models.DateTimeField(auto_now=True, verbose_name="Дата обновления профиля")

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'sex', 'address', 'phone_number']

    class Meta:
        verbose_name = "профиль покупателя"
        verbose_name_plural = "профиля покупателей"

    def get_full_name(self):
        # The user is identified by their email address
        return '{} {}'.format(self.last_name, self.first_name)
    get_full_name.admin_order_field = 'profile_create'
    get_full_name.short_description = 'Фамилия и имя'

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        # __unicode__ on Python 2
        return self.email

    def get_sex(self):
        return self.get_sex_display()
    get_sex.admin_order_field = 'sex'
    get_sex.short_description = 'Стать покупателя'

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

buyer/forms.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django import forms
from .models import BuyerUser
from .admin import BuyerCreationForm


class CalendarWidget(forms.DateInput):
    class Media:
        css = {
            'all': ('css/jquery-ui.min.css',)
        }
        js = ('js/jquery-ui.js', 'js/datepicker-uk.js', 'js/datepicker-ru.js', 'js/datepicker-widget.js')


class RadioSelectWidget(forms.RadioSelect):
    class Media:
        css = {'all': ('css/radio_select.css', '//goo.gl/mTc43h')}


class BuyerLoginForm(forms.Form):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    email = forms.EmailField(label="", widget=forms.EmailInput(attrs={'placeholder': 'E-Mail',
                                                                      'id': 'userid',
                                                                      'name': 'userid',
                                                                      'title': 'E-Mail'}))

    password = forms.CharField(label="", widget=forms.PasswordInput(attrs={'placeholder': '•••••••••••',
                                                                           'id': 'pw',
                                                                           'name': 'pw',
                                                                           'title': 'password',
                                                                           'autocomplete': 'off'}))

    def clean_email(self):
        email = self.cleaned_data.get("email")
        email_exists = BuyerUser.objects.filter(email=email).exists()
        if not email_exists:
            raise forms.ValidationError("Такой email не зареєстрован.", code='email_exists')
        else:
            return email

    def clean_password(self):
        password = self.cleaned_data.get("password")
        email = self.cleaned_data.get("email")
        buyer = BuyerUser.objects.filter(email=email)
        if buyer.exists() and buyer[0].check_password(password):
            return password
        elif buyer.exists() and password is not None:
            raise forms.ValidationError("Неверный пароль!")


class BuyerRegisterForm(BuyerCreationForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    sex = forms.ChoiceField(label="Пол", choices=(('Man', 'Мужчина'), ('Woman', 'Женщина')),
                            widget=RadioSelectWidget(attrs={'class': 'option-input radio'}))

    class Meta(BuyerCreationForm.Meta):
        model = BuyerUser

        widgets = {'email': forms.EmailInput(attrs={'class': 'form-control', 'rows': 4,
                                                    'placeholder': 'введите E-mail'}),
                   'first_name': forms.TextInput(attrs={'class': 'form-control', 'rows': 4,
                                                        'placeholder': "введите имя"}),
                   'last_name': forms.TextInput(attrs={'class': 'form-control', 'rows': 4,
                                                       'placeholder': "введите фамилию"}),
                   'date_of_birth': CalendarWidget(format='%Y-%m-%d',
                                                   attrs={'class': 'form-control',
                                                          'id': 'id_date_of_birth',
                                                          'placeholder': 'дата рождения',
                                                          'autocomplete': 'off'}),
                   'phone_number': forms.TextInput(attrs={'class': 'form-control', 'rows': 4,
                                                          'placeholder': "введите номер телефона"}),
                   # 'sex': RadioSelectWidget(attrs={'class': 'option-input radio'})
}

        labels = {'email': "E-mail",
                  'first_name': "Имя",
                  'last_name': "Фамилия",
                  'date_of_birth': "Дата рождения",
                  # 'sex': "Пол",
                  'phone_number': "Номер телефона"}

        help_texts = {'phone_number': 'формат ввода номера телефона +380967578910'}


class BuyerUpdateForm(BuyerRegisterForm):
    password = forms.CharField(label="Старый пароль",
                               widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'введите cтарый пароль',
                                                                 'autocomplete': 'off'}))
    email = forms.CharField(label="E-mail", disabled=True, widget=forms.TextInput(
        attrs={'class': 'form-control',
               'rows': 4}))

    class Meta(BuyerRegisterForm.Meta):
        model = BuyerUser
        fields = BuyerRegisterForm.Meta.fields + ('address', 'password', )

    def clean_password(self):
        password = self.cleaned_data.get("password")
        email = self.cleaned_data.get("email")
        user = BuyerUser.objects.get(email=email)
        if user is not None and user.check_password(password):
            return password
        elif password is not None:
            raise forms.ValidationError("Старый пароль не верен!")

buyer/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.contrib import auth
from django.core.context_processors import csrf
from .models import BuyerUser
# from .forms import (ProfileCreationForm,
#                            ProfileUpdateForm)
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.urlresolvers import reverse
from django.conf import settings

from .forms import (BuyerLoginForm, BuyerRegisterForm, BuyerUpdateForm)


User = get_user_model()


def login(request):

    if request.is_ajax() and request.method == 'POST':
        data = dict()
        form = BuyerLoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = auth.authenticate(username=email, password=password)

            if user is not None and user.is_active:
                del request.session[settings.CART_SESSION_ID]
                auth.login(request, user)
                data['form_valid'] = True
                path = request.GET.get('next')

                if path != reverse('buyer:login'):
                    redirect_path = path
                else:
                    redirect_path = '/'

                data['redirect_path'] = redirect_path

        data['form_html'] = render_to_string('login.html', {'login_form': form}, request=request)

        return JsonResponse(data)

    return redirect('/')


def logout(request):
    # messages.success(request, 'Щастливо, ' + request.user.username + '!', extra_tags='success')
    auth.logout(request)
    path = request.GET.get('next', '')
    if path:
        return redirect(path)
    else:
        return redirect(reverse('menu:homepage'))


def register(request):

    form = BuyerRegisterForm()
    if request.POST:
        form = BuyerRegisterForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password2']
            buyer = BuyerUser(email=form.cleaned_data['email'], first_name=form.cleaned_data['first_name'],
                              last_name=form.cleaned_data['last_name'],
                              date_of_birth=form.cleaned_data['date_of_birth'],
                              sex=form.cleaned_data['sex'],
                              phone_number=form.cleaned_data['phone_number'],
                              address=form.cleaned_data['address'])
            buyer.set_password(password)
            buyer.save()

            new_buyer = auth.authenticate(username=buyer.email, password=password)

            auth.login(request, new_buyer)
            # messages.success(request, 'Дякую, що долучилися до нас, ' + new_profile.user.username + '!',
            #                  extra_tags='success')
            return redirect(reverse('menu:homepage'))
        else:
            form = form

    title = "Форма регистрации"
    button_create = 'РЕГИСТРИРОВАТЬСЯ'

    context = {
        'title': title,
        'button_create': button_create,
        'form': form,
        }
    return render(request, 'register.html', context)


def update(request):
    instance = get_object_or_404(User, email=request.user)
    form = BuyerUpdateForm(request.POST or None, instance=instance,
                           initial={'address': instance.address})
    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.instance)
        # messages.success(request, _('Ви змінили свій профіль, ' + instance.username + '!'),
        #                  extra_tags='success')
        return redirect(reverse('menu:homepage'))
    else:
        form = form
    title = "Форма для изменения профиля '{}'".format(instance.get_full_name())
    button_update = 'ИЗМЕНИТЬ'
    button_delete = 'УДАЛИТЬ'
    context = {
        'title': title,
        'button_create': button_update,
        'button_delete': button_delete,
        'form': form,
        'profile': instance,
        }
    return render(request, 'register.html', context)


def delete(request, id=None):
    if request.is_ajax():
        data = dict()
        instance = get_object_or_404(User, id=id)
        title = "Вы уверены, что хотите удалить свой профиль '{}'?".format(instance.get_full_name())
        button_delete = 'УДАЛИТЬ ПРОФИЛЬ'
        button_cancel = 'ОТМЕНА'
        context = {
            'title': title,
            'button_delete': button_delete,
            'button_cancel': button_cancel
            }

        data['delete_form'] = render_to_string('delete_form.html', context, request=request)

        if request.POST:
            instance.delete()
            data['is_data'] = True
            data['redirect_path'] = reverse('menu:homepage')
            # messages.success(request, _('Користувач \'' + name + '\' видалений!'), extra_tags='success')

        return JsonResponse(data)

    return redirect(reverse('menu:homepage'))

buyer/templates/buyer/delete_form.html
<form method="post" action="{% url 'buyer:delete' request.user.id %}" class="js-profile-delete-form">
    {% csrf_token %}

    <div class="modal-body">
        <p class="lead">
            <strong>{{ title }}</strong>
        </p>
    </div>

    <div class="clearfix cart-total">
         <span class="cart-return-link">
             <span class="btn-link btn-link-gray">
                 <a href="#close-modal" rel="modal:close" class="btn-link-i" name="close">{{ button_cancel }}</a>
             </span>
         </span>

        <span class="cart-submit">
             <span class="btn-link-green btn-link">
                 <button class="btn-link-i" id="popup-checkout" type="submit">{{ button_delete }}</button>
             </span>
         </span>
    </div>
</form>

buyer/templates/buyer/login.html
{% load staticfiles %}{% load i18n %}


<form id="login" class="yform" method="post" action="{% url 'buyer:login' %}?next={{ request.path }}">

    {% csrf_token %}

    {% for field in login_form %}

        {% if field.errors %}
            <div class="form-group has-error">

                {% for error in field.errors %}

                    <label class="control-label errorlist"><em>{{ error }}</em></label>

                {% endfor %}

            </div>
        {% endif %}

        <div class="type-text">
            {{ field }}
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>

    {% endfor %}

    <span class="cart-submit" style="width: 100%; padding: 5px 0 0;">
        <span class="btn-link-green btn-link" style="width: 100%;">
            <button class="btn-link-i" id="popup-checkout" type="submit" style="width: 100%;">АВТОРИЗОВАТЬСЯ</button>
        </span>
    </span>
</form>
<div class="aligned-center">
   <a class="check-edit-order-link" href="{% url 'buyer:password_reset' %}">{% trans 'Забыли пароль?' %}</a>
</div>


buyer/templates/buyer/register.html
{% extends "base.html" %}{% load staticfiles %}


{% block title %}{{ title }}{% endblock %}


{% block script %}

    <script src="{% static 'js/jquery.modal.js' %}"></script>

    <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery.modal.css' %}"/>

     {{ form.media }}

{% endblock %}


{% block register %}

    <div class="page_margins">
        <div class="page">
            <div class="pagePadding">
                <div id="col3" role="main">
                    <div id="col3_content" class="clearfix">
                        <div class="boxen">
                            <div class="my-shop box">

                                <div class="form-title">
                                    <h3>{{ title }}</h3>
                                </div>

                                <div class="forms">

                                    <form class="register yform" method="post" action="">

                                        {% csrf_token %}

                                        {% for field in form %}

                                            {% if field.errors %}
                                                <div class="form-group has-error">

                                                    {% for error in field.errors %}

                                                        <label class="control-label errorlist"><em>{{ error }}</em></label>

                                                    {% endfor %}

                                                </div>
                                            {% endif %}

                                            <div class="type-text">

                                                {{ field.label_tag }}

                                                {{ field }}

                                                {% if field.help_text %}
                                                    <p class="help">{{ field.help_text|safe }}</p>
                                                {% endif %}

                                            </div>

                                        {% endfor %}

                                        <div class="clearfix cart-total">
                                             <span class="cart-return-link">
                                                 <span class="btn-link btn-link-gray">
                                                     <a href="{% url 'menu:homepage' %}" class="btn-link-i" name="close">ВЕРНУТЬСЯ НАЗАД</a>
                                                 </span>
                                             </span>

                                            {% if button_delete %}

                                                <span class="cart-return-link delete">
                                                     <span class="btn-link btn-link-gray">
                                                         <a href="{% url 'buyer:delete' request.user.id %}" class="delete-ajax btn-link-i" name="close">{{ button_delete }}</a>
                                                     </span>
                                                 </span>

                                            {% endif %}

                                            <span class="cart-submit">
                                                 <span class="btn-link-green btn-link">
                                                     <button class="btn-link-i" id="popup-checkout" type="submit">{{ button_create }}</button>
                                                 </span>
                                             </span>
                                        </div>
                                    </form>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- AJAX response must be wrapped in the modal's root class. -->
    <div class="modal">
        <div class="modal-content">
            <p>Second AJAX Example!</p>
        </div>
    </div>

{% endblock %}


{#{% block register %}#}
{##}
{#    <div class="page_margins">#}
{#        <div class="page">#}
{#            <div class="pagePadding">#}
{#                <div id="col3" role="main">#}
{#                    <div id="col3_content" class="clearfix">#}
{#                        <div class="boxen">#}
{#                            <div class="my-shop box">#}
{##}
{#                                <div class="form-title">#}
{#                                    <h3>{{ title }}</h3>#}
{#                                </div>#}
{##}
{#                                <div class="forms">#}
{##}
{#                                    <form class="register yform" method="post" action="">#}
{##}
{#                                        {% csrf_token %}#}
{##}
{#                                        {% for field in form %}#}
{##}
{#                                            {% if field.errors %}#}
{#                                                <div class="form-group has-error">#}
{##}
{#                                                    {% for error in field.errors %}#}
{##}
{#                                                        <label class="control-label errorlist"><em>{{ error }}</em></label>#}
{##}
{#                                                    {% endfor %}#}
{##}
{#                                                </div>#}
{#                                            {% endif %}#}
{##}
{#                                            <div class="type-text">#}
{##}
{#                                                {{ field.label_tag }}#}
{##}
{#                                                {{ field }}#}
{##}
{#                                                {% if field.help_text %}#}
{#                                                    <p class="help">{{ field.help_text|safe }}</p>#}
{#                                                {% endif %}#}
{##}
{#                                            </div>#}
{##}
{#                                        {% endfor %}#}
{##}
{#                                        <div class="clearfix cart-total">#}
{#                                             <span class="cart-return-link">#}
{#                                                 <span class="btn-link btn-link-gray">#}
{#                                                     <a href="{% url 'menu:homepage' %}" class="btn-link-i" name="close">ВЕРНУТЬСЯ НАЗАД</a>#}
{#                                                 </span>#}
{#                                             </span>#}
{##}
{#                                            {% if button_delete %}#}
{##}
{#                                                <span class="cart-return-link delete">#}
{#                                                     <span class="btn-link btn-link-gray">#}
{#                                                         <a id="delete-ajax" href="{% url 'buyer:delete' request.user.id %}" class="btn-link-i" name="close">{{ button_delete }}</a>#}
{#                                                     </span>#}
{#                                                 </span>#}
{##}
{#                                            {% endif %}#}
{##}
{#                                            <span class="cart-submit">#}
{#                                                 <span class="btn-link-green btn-link">#}
{#                                                     <button class="btn-link-i" id="popup-checkout" type="submit">{{ button_create }}</button>#}
{#                                                 </span>#}
{#                                             </span>#}
{#                                        </div>#}
{#                                    </form>#}
{##}
{#                                </div>#}
{##}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#   #}
{#    <!-- AJAX response must be wrapped in the modal's root class. -->#}
{#    <div class="modal">#}
{#        <div class="modal-content">#}
{#            <p>Second AJAX Example!</p>#}
{#        </div>#}
{#    </div>#}
{##}
{#    <script>#}
{#        $(function(){#}
{#            // Open modal in AJAX callback#}
{#            $('#delete-ajax').click(function(event) {#}
{#                event.preventDefault();#}
{#                console.log(event.preventDefault())#}
{#                $.get(this.href, function(html) {#}
{#                    console.log(html)#}
{#                    $('.modal').modal("show");#}
{#                    $('.modal-content').html(html.delete_form);#}
{#                });#}
{#            });#}
{#        })#}
{#    </script>#}
{##}
{#{% endblock %}#}