cart/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^remove/(?P<product_id>\d+)/(?P<size>.*)/$', views.cart_remove, name='remove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^ordering/$', views.ordering, name='ordering'),
]

miltec/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('menu.urls', namespace='menu')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^buyer/', include('buyer.urls', namespace='buyer')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^search-products/$', views.search, name='search'),
    url(r'^product-list/(?P<slug>.*)/$', views.product_list, name='product_list'),
    url(r'^(?P<slug>.*)/$', views.product_details, name='product'),

]

product/models.py
# -*- encoding: utf-8 -*-
"""
This module create models for products.
"""

from __future__ import unicode_literals

import os
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
from menu.models import (Category, Item)
from cart.forms import CartAddProductForm
from django.core.exceptions import ValidationError


def upload_location(instance, filename):
    path = 'upload/products'
    if instance.category:
        dir = instance.category.title
    else:
        dir = instance.item.title
    return os.path.join(path, str(dir), str(instance.article), 'detail', str(filename))


def upload_location2(instance, filename):
    path = 'upload/products'
    if instance.category:
        dir = instance.category.title
    else:
        dir = instance.item.title
    return os.path.join(path, str(dir), str(instance.article), str(filename))


class Product(models.Model):
    """
    Stores a product.
    """
    title = models.CharField(max_length=50, verbose_name="Назва товару")
    description = models.TextField(max_length=5000, verbose_name="Опис товару", blank=True, null=True)
    details = models.TextField(max_length=5000, verbose_name="Деталі товару", default='')
    article = models.PositiveIntegerField(verbose_name="Артикль товару", default=00000000)

    sold = models.BooleanField(verbose_name="Проданий", default=False)
    slug = models.SlugField(verbose_name="Ім`я товару транслітом", unique=True)

    price = models.DecimalField(verbose_name="Ціна для всій відвідувачів",
                                max_digits=8, decimal_places=2)
    price_for_users = models.DecimalField(verbose_name="Ціна для зареєстрованих відвідувачів",
                                          max_digits=10, decimal_places=2)

    image = models.ImageField(verbose_name="Картинка", upload_to=upload_location, width_field="width_field",
                              height_field="height_field", blank=True, null=True,
                              help_text="Зображення товару")
    image_large = models.ImageField(verbose_name="Велика картинка", upload_to=upload_location2,
                                    width_field="width_field", height_field="height_field", blank=True, null=True,
                                    help_text="Зображення товару для детального перегляду")
    width_field = models.IntegerField(default=0, verbose_name="Ширина картинки в пікселях")
    height_field = models.IntegerField(default=0, verbose_name="Висота картинки в пікселях")

    create = models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")
    update = models.DateTimeField(auto_now=True, verbose_name="Дата оновлення")

    category = models.ForeignKey(Category, related_name="products",
                                 verbose_name="Категорія товару", blank=True, null=True)

    item = models.ForeignKey(Item, related_name="products",
                             verbose_name="Підкатегорія товару", blank=True, null=True)

    class Meta:
        """
        Change db_table name, verbose_name, verbose_name_plural
        """
        ordering = ['id']
        db_table = "products"
        verbose_name = "Товар"
        verbose_name_plural = "Товари"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.category:
            object_id = self.category.id
        elif self.item:
            object_id = self.item.id
        else:
            object_id = self.article
        self.slug = "{}-{}".format(slugify(self.title, allow_unicode=True), object_id)

        if not self.category:
            self.category = self.item.category()

        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product:product', kwargs={'slug': self.slug})

    def get_sizes(self):
        instance_sizes = self.item.sizes.filter(size_count__product=self)
        if not instance_sizes.exists():
            return None
        else:
            return instance_sizes

    def get_cart_form(self, request_form=None):
        if request_form is None:
            cart_form = CartAddProductForm()
        else:
            cart_form = CartAddProductForm(request_form)
        sizes = self.get_sizes()
        cart_form.fields['quantity'].choices = [(i, str(i)) for i in range(1, 21)]
        if sizes:
            size_choices = [(sizes[i], str(sizes[i])) for i in range(len(sizes))]
            cart_form.fields['size'].choices = size_choices
        else:
            cart_form.fields['size'].choices = []
        return cart_form

    def get_item_products(self):
        all_products = self.item.products.all()
        return all_products


class Size(models.Model):
    title = models.CharField(verbose_name="Размер", max_length=10, unique=True)
    items = models.ManyToManyField(Item, related_name="sizes",
                                   verbose_name="Категория размера")

    class Meta:
        """
        Size products for item
        """
        ordering = ['title']
        db_table = "sizes"
        verbose_name = "Размер"
        verbose_name_plural = "Размеры"

    def __str__(self):
        return str(self.title)

    def get_items(self):
        return " | \n".join([i.title for i in self.items.all()])

    get_items.short_description = 'Список категорий'


class SizeCount(models.Model):
    size = models.ForeignKey(Size, verbose_name="Размер", related_name='size_count', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name="Товар", related_name='size_count', on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name="Количество", default=0)

    class Meta:
        """
        Count sizes of products for item
        """
        verbose_name = "Количество размеров"
        verbose_name_plural = "Количества размеров"

    def __str__(self):
        return "Количество товаров размера - {}: {}".format(self.size.title, self.count)

    def clean(self):
        # Don't allow draft entries to have a pub_date.
        if self.product.item not in self.size.items.all():
            raise ValidationError(
                'Нет в категории товара размера: %(value)s',
                params={'value': self.size.title},)
        if self.size in self.product.size_count.filter(size=self.size):
            raise ValidationError(
                'В товара уже есть размер: %(value)s',
                params={'value': self.size.title},)

    def save(self, *args, **kwargs):
        if self.product.item in self.size.items.all():
            if self.product.size_count.filter(size=self.size).exists():
                raise ValueError('В товара уже есть размер:: %s' % self.size.title)
        else:
            raise ValueError('Нет в категории товара размера: %s' % self.size.title)

        super(SizeCount, self).save(*args, **kwargs)

product/views.py
from django.shortcuts import redirect

from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from menu.models import Item
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import Product


def pagination_products(request, products_all, count_products=2):

    paginator = Paginator(products_all, count_products)
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
        # print(articles.page_range)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)
    return products


def ordering_too(request, products_all, default_ordering='price'):

    # ordering products
    ordering_type = request.GET.get('ordering', '')

    if ordering_type != '' and ordering_type != request.session.get('ordering'):
        request.session['ordering'] = ordering_type
        products = products_all.order_by(ordering_type)
    elif request.session.get('ordering'):
        products = products_all.order_by(request.session.get('ordering'))
    else:
        products = products_all.order_by(default_ordering)

    return products


def view_page(request):
    # views products standard or grid
    view = request.GET.get('view', '')
    if view != '':
        request.session['view'] = view


def product_list(request, slug=None):

    if request.is_ajax():
        data = dict()
        item = get_object_or_404(Item, slug=slug)

        # ordering products
        products = item.get_all_products()
        list_product = ordering_too(request, products)

        # view products
        view_page(request)

        # pagination products
        products = pagination_products(request, list_product, 10)

        context = {'products': products,
                   'item': item}

        data['html_items'] = render_to_string('product_list.html',
                                              context,
                                              request=request)
        data['is_data'] = True

        return JsonResponse(data)
    else:
        return redirect(reverse('menu:shop'))


def product_details(request, slug=None):
    if request.is_ajax():
        data = dict()
        product = get_object_or_404(Product, slug=slug)

        products = pagination_products(request, product.get_item_products(), 1)

        context = {'products': products,
                   'product': product,
                   'item': product.item}

        if products.has_next():
            context['next_slug'] = products.paginator.page(products.next_page_number()).object_list[0].slug

        if products.has_previous():
            context['previous_slug'] = products.paginator.page(products.previous_page_number()).object_list[0].slug

        data['html_items'] = render_to_string('partial_product.html',
                                              context,
                                              request=request)
        data['is_data'] = True

        return JsonResponse(data)

    return redirect(reverse('menu:shop'))


def search(request):

    if request.is_ajax():
        # search products
        query = request.GET.get('q')
        data = dict()
        context = {
            'search': True}

        if query and query.isspace() is False:
            products_search = Product.objects.filter(
                Q(title__icontains=query) |
                Q(description__icontains=query)).distinct()

            view_page(request)

            if products_search:
                products_ordering = ordering_too(request, products_search)
                products = pagination_products(request, products_ordering, 10)

                context.update({
                    'products': products,
                    'item': {
                        'title': 'Результат поиска',
                        'returned_title': 'Ваш запрос о поиске » {} « вернул следующее.'.format(query)}})
            else:
                context['item'] = {'title': 'Результат поиска',
                                   'returned_title': 'Нет результатов поиска ...'}

            data['is_data'] = True
            data['html_items'] = render_to_string('product_list.html',
                                                  context,
                                                  request=request)
        else:
            data['is_data'] = False

        return JsonResponse(data)

    else:
        return redirect(reverse('menu:shop'))

product/templates/product/partial_product.html
{% load staticfiles %}{% load product_tags %}



<div id="col3_content" class="clearfix">

    <div class="breadcrumbBar clearfix">

        {% include 'breadcrum.html' %}
        {% include 'product_pagination.html' %}

    </div>

    <!-- begin: product-row_detail_?.html -->
        <div class="product-details">
            <dl>
                <dt title="{{ product.title|upper }}">
                <h1><span itemprop="name">{{ product.title|upper }}</span></h1>
                </dt>

                <!-- begin include: pic_detail_?.html -->
                <dd class="image" note="has_large">
                    <div class="imageContainer" style="position: relative;">
                        <a href="{% if product.image_large %}{{ product.image_large.url }}{% endif %}" onclick="return false" data-spzoom style="outline-style: none; text-decoration: none; cursor: crosshair; display: block; position: relative; height: 200px; width: 160px;" title="{{ product.title|upper }}">
                            <img itemprop="image" class="thumb photo" src="{{ product.image.url }}" alt="{{ product.title|upper }}" style="opacity: 1;">
                        </a>
                    </div>

                    <a href="{% if product.image_large %}{{ product.image_large.url }}{% endif %}" class="tagEnlarge" title="{{ product.title|upper }}" rel="prettyPhoto[gal]">
                        <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-magnifier">
                        <u>Увеличить фото</u>
                    </a>
                </dd>

                <!-- SpZoom -->
                <link type="text/css" href="{% static 'css/jquery.spzoom.css' %}" rel="stylesheet">
                <script src="{% static 'js/jquery.spzoom.js' %}"></script>
                <!-- prettyPhoto -->
                <link rel="stylesheet" href="{% static 'css/prettyPhoto.css' %}" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
                <script src="{% static 'js/jquery.prettyPhoto.js' %}" type="text/javascript" charset="utf-8"></script>
                <!-- Accessible Tabs -->
                <script src="{% static 'js/jquery.tabs.js' %}" type="text/javascript" charset="utf-8"></script>

                <script type="text/javascript">

                    // Scaling for product-details image
                    $('#col3_content div > dl > dd.image > div > a[data-spzoom]').spzoom({
                        width: 450,
                        height: 500,
                        titlePosition: 'top'
                    });

                    $("#col3_content div > dl > dd.image > a[rel^='prettyPhoto']").prettyPhoto({
                        theme: 'pp_default',	/* pp_default / light_rounded / dark_rounded / light_square / dark_square / facebook */
                        hideflash: false, /* Hides all the flash object on a page, set to TRUE if flash appears over prettyPhoto */
                        social_tools: false, /* html or false to disable */
                        deeplinking: false, /* Allow prettyPhoto to update the url to enable deeplinking. */
                        ie6_fallback: true,
                        overlay_gallery: false /* If set to true, a gallery will overlay the fullscreen image on mouse over */,
                        iframe_markup:'<div class="iOSscroll" style="width:{width}px;height:{height}px;"><iframe src ="{path}" width="{width}" height="{height}" frameborder="no"></iframe></div>' /* Bugfix for iOS Touch devices to be able to scroll */
                    });

                    $("#col3 div.jquery_tabs")[0] && ($("#col3 div.jquery_tabs").accessibleTabs({
                        tabhead: "h4",
                        tabbody: ".tabs-content",
                        currentInfoText: "",
                        fx: "fadeIn",
                        autoAnchor: !0,
                        saveState: !0
                    }),
                            $(".jquery_tabs ul.tabs-list li").first().addClass("firstTab"),
                            $(".jquery_tabs ul.tabs-list li").last().addClass("lastTab"));


                    $('div.imageContainer img.thumb').load( function() {
                        $('div.imageContainer img.thumb').each(function() {
                            var containerHeight = $('div.imageContainer').height(); // Current height of container
                            var containerWidth = $('div.imageContainer').width(); // Current width of container
                            var imageWidth = $(this).width();  // Current image height
                            var imageHeight = $(this).height();  // Current image height

                            if(containerHeight>imageHeight)
                            {
                                var newTop = imageHeight + 10;
                                $('head').append('<style type=\"text/css\">' +
                                        'div.imageContainer img.thumb { width: '+containerWidth+'px !important; }' +
                                        'div.product-details dd.image a.tagEnlarge { top: '+newTop+'px  !important;}' +
                                        '</style>'
                                );
                            }
                            else if(imageHeight>containerHeight)
                            {
                                var newTop = imageHeight + 10;
                                var newHeight = imageHeight + 35;
                                $('head').append('<style type=\"text/css\">' +
                                        'div.imageContainer img.thumb,' +
                                        'div.imageContainer .jqZoomPup img,' +
                                        '.product-details .image div.imageContainer { text-align: left; }' +
                                        '.product-details .image div.imageContainer { height: '+imageHeight+'px !important;}' +
                                        '.product-details .image div.imageContainer a.jqzoom { height: '+imageHeight+'px !important; width: '+containerWidth+'px !important;}' +
                                        '.product-details .image div.imageContainer a.jqzoom div.jqZoomPup img { height: '+imageHeight+'px !important; width: '+imageWidth+'px !important;}' +
                                        'div.product-details dd.image a.tagEnlarge { top: '+newTop+'px  !important;}' +
                                        'div.product-details dd.image { height: '+newHeight+'px  !important;}' +
                                        '</style>'
                                );
                            }
                        });
                    });

                </script>

                <dd class="articleNr">
                    <label>Article No.:</label>
                    <div itemprop="{{ product.id }}">
                        {{ product.article }}
                    </div>
                </dd>

                <!-- EIDAMO_LIST_INQUIRY_START:1 -->
                <dd class="price" id="price_1" style="">
                    <span class="current_price" itemprop="offers" itemscope="" itemtype="">

                         {% include "product_prices.html" %}
                        {% include "cart_form.html" %}

                    </span>
                </dd>
            </dl>
            </dl>

        </div>
    <!-- end: product-row_detail_?.html -->

    <!-- begin: jquery tabs -->
    <div class="jquery_tabs">
        <!-- begin: product-description_?.html -->
        {% if product.description %}
            <h4>Описание</h4>
            <div class="tabs-content">
		<dl class="specifications">
		  <dd>
                    <p>{{ product.description|safe }}</p>
		  </dd>
		</<dl>
            </div>
        {% endif %}
        <!-- end: product-description_?.html -->

        <!-- begin: product-specifications_?.html -->
        {% if product.details %}
            <h4>Детали</h4>
            <div class="tabs-content">
                {{ product.details|safe }}
            </div>
        {% endif %}
    </div>
    <!-- end: jquery tabs -->

    <div class="bottomToolBar clearfix">
        <div class="buttonsContainer" style="float:left;">
            <a href="#" onclick="history.go(-1)" class="formButton">
                <span><b>back</b></span>
            </a>
        </div>

        <!-- begin: nav_detail_bottom_?.html -->
        {% include 'product_pagination.html' %}
        <!-- end: nav_detail_bottom_?.html -->

    </div>
</div>
<!-- end: article detail specific content -->

<div id="ie_clearing">&nbsp;</div>
<!-- End: IE Column Clearing -->

product/templates/product/product_list.html
{% load staticfiles %}


<div id="col3_content" class="clearfix">

    <!-- Start des Formulars (anscheinend nur in shop_list nötig)-->
 <div>
        <div class="breadcrumbBar clearfix">
            {% include 'breadcrum.html' %}

            {% include 'tools_pagination.html' %}
        </div>

        {% if not search %}
            <div class="categories">
                <!-- Category: Title Only -->
                <div class="category-current">
                    <div class="rubImg-container noRubImg"></div>
                    <h2>{{ item.title }}</h2>
                </div>
            </div>
        {% endif %}

        <div class="toolBar clearfix">
            <div class="tools sortOptions-viewStandard">
                <span><b>Сортировать:</b></span>

                {% if request.session.ordering != '-title' %}
                    <a href="{% if search %}{% url 'product:search' %}?page={{ products.number }}&ordering=-title{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ products.number }}&ordering=-title{% endif %}"
                       class="sortTitleDesc {% if request.session.ordering == 'title' %}active{% endif %}">
                        <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-sort-alphabet">
                        <u>Название</u>
                    </a>
                {% elif request.session.ordering != 'title' %}
                    <a href="{% if search %}{% url 'product:search' %}?page={{ products.number }}&ordering=title{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ products.number }}&ordering=title{% endif %}"
                       class="sortTitleAsc {% if request.session.ordering == '-title' %}active{% endif %}">
                        <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-sort-alphabet-descending">
                        <u>Название</u>
                    </a>
                {% endif %}

                {% if request.session.ordering != '-price' %}
                    <a href="{% if search %}{% url 'product:search' %}?page={{ products.number }}&ordering=-price{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ products.number }}&ordering=-price{% endif %}"
                       class="sortPriceAsc {% if request.session.ordering == 'price' %}active{% endif %}">
                        <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-sort-number">
                        <u>Цена</u>
                    </a>
                {% elif request.session.ordering != 'price' %}
                    <a href="{% if search %}{% url 'product:search' %}?page={{ products.number }}&ordering=price{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ products.number }}&ordering=price{% endif %}"
                       class="sortPriceDesc {% if request.session.ordering == '-price' %}active{% endif %}">
                        <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-sort-number-descending">
                        <u>Цена</u>
                    </a>
                {% endif %}

            </div>

            <div class="tools float_right">
                <a href="{% if search %}{% url 'product:search' %}?page={{ products.number }}&view=standard{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ products.number }}&view=standard{% endif %}"
                   title="List View" class="display-viewStandard {% if request.session.view != 'grid' %}display-viewStandard-active{% endif %}">
                    <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-edit-list">
                </a>
                <a href="{% if search %}{% url 'product:search' %}?page={{ products.number }}&view=grid{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ products.number }}&view=grid{% endif %}"
                   title="Grid View" class="display-viewGrid {% if request.session.view == 'grid' %}display-viewGrid-active{% endif %}">
                    <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-grid">
                </a>
            </div>

        </div>

        {% if request.session.view != 'grid' %}

            {% include 'products_view_standard.html' %}

        {% else %}

            {% include 'products_view_grid.html' %}

        {% endif %}

  </div>


    {% if products.has_other_pages %}

        <div class="bottomToolBar clearfix" style="border-bottom: 1px solid #d6d6d6;">

        <!-- begin: breadcrumbs: nav_list_top_?.html -->
        {% include 'tools_pagination.html' %}
        <!-- begin: nav_list_bottom_?.html -->

        <div class="bottomToolBar clearfix pagination">
            <span class="product-list-status">page:

                {% for page in products.paginator.page_range %}
                    {% if page == products.number %}
                        <a class="os_pages active" href="{% if search %}{% url 'product:search' %}?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% endif %}">
                            {{ page }}
                        </a> |
                    {% else %}
                        <a class="os_pages" href="{% if search %}{% url 'product:search' %}?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% else %}{% url 'product:product_list' item.slug %}?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% endif %}">
                            {{ page }}
                        </a> |
                    {% endif%}
                {% endfor %}

                </span>
            <span class="product-list-status float_right">{{ products.number }}-{{ products.paginator.num_pages }}| {{ products.paginator.count }} Article</span>
        </div>

    {% endif %}

    </div>
    <div id="ie_clearing">&nbsp;</div>
    <!-- End: IE Column Clearing -->

</div>

product/templates/product/product_pagination.html
{% load staticfiles %}


{% if products.has_other_pages %}

    <div class="tools pagination float_right" style="padding-top:5px;">

        {% if products.has_previous %}

            <a href="{% url 'product:product' previous_slug %}?page={{ products.previous_page_number }}"
               title="Return" class="prevPage">
                <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-arrow-180">
            </a>

        {% endif %}

        {% if products.has_next %}

            <a href="{% url 'product:product' next_slug %}?page={{ products.next_page_number }}"
               title="Continue" class="nextPage">
                <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-arrow">
            </a>

        {% endif %}

    </div>

{% endif %}

product/templates/product/product_prices.html
{% load staticfiles %}{% load product_tags %}


{% if request.user.is_authenticated %}

    <span class="price" itemprop="price" style="color: green">

                    {{ product.price_for_users }}

                    </span>
    <span class="currency" style="color: green">EUR</span>

     <div>
                    <span class="new-price">

                    <em><b>{{ product.price_for_users|price_exchange:exchange }} UAH </b></em>

                    </span>
     </div>

{% else %}

    <span class="price" itemprop="price">
        {{ product.price}}
    </span>

    <span class="currency">EUR</span>

    <div>
        <span class="new-price">
            <em><b>{{ product.price|price_exchange:exchange }} UAH </b></em>
        </span>
    </div>

    <div>
        <span style="color: #c22727">
            <b>(оптовая цена после регистрации)</b>
        </span>
    </div>

{% endif %}

<br/>