buyer/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'password_reset_form.html',
                                                          'email_template_name': 'password_reset_email.html',
                                                          'html_email_template_name': 'password_reset_email.html',
                                                          'subject_template_name': 'password_reset_subject.txt',
                                                          'post_reset_redirect': 'buyer:password_reset_done'},
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'password_reset_done.html',
                                                                    'current_app': 'buyer'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name': 'password_reset_confirm.html',
         'post_reset_redirect': 'buyer:password_reset_complete'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^update/$', views.update, name='update'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^logout/$', views.logout, name='logout'),
    ]


cart/urls.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals


from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='detail'),
    url(r'^remove/(?P<product_id>\d+)/(?P<size>.*)/$', views.cart_remove, name='remove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^ordering/$', views.ordering, name='ordering'),
]

menu/urls.py
from django.conf.urls import url
from menu import views


urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^shop/(?P<slug>.*)/category/$', views.items_list, name='items_list'),
]

miltec/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('menu.urls', namespace='menu')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^buyer/', include('buyer.urls', namespace='buyer')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^search-products/$', views.search, name='search'),
    url(r'^product-list/(?P<slug>.*)/$', views.product_list, name='product_list'),
    url(r'^(?P<slug>.*)/$', views.product_details, name='product'),

]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta property="og:image" content="{% static 'img/logo.png' %}">

    <title>
        {% block title %}

            Sturm MIL-TEC® Online-Shop

            (www.sturm-miltec.de)

        {% endblock %}
    </title>

    <meta name="publisher" content="Sturm Handels GmbH">

    <!-- ICONS -->
    <!-- speed-dial-icon -->
    <link rel="icon" href="{% static 'img/appletouch.ipad-retina.png' %}" type="image/png" media="(view-mode:minimized)">

    <meta http-equiv="preview-refresh" content="3600">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'img/icon.ico' %}">
    <link rel="icon" href="{% static 'img/icon.ico' %}" type="image/ico">

    <!-- apple-touch-icon -->
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/appletouch.ipad-retina.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/appletouch.iphone4.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/appletouch.ipad.png' %}">
    <link rel="apple-touch-icon"  href="{% static 'img/appletouch.iphone.png' %}">

    <link href="{% static 'css/my_css.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/buyer.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom Design -->
    <link type="text/css" href="{% static 'css/3col_fullheight.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'css/widget70.css' %}" rel="stylesheet">


    <!--[if IE]>
	<link href="/shop/images/img002/style/css/yaml/iehacks.css" rel="stylesheet" type="text/css" />
	<![endif]-->

    <!--[if lte IE 7]>
	<link href="/shop/images/img002/style/css/patches/patch_3col_fullheight.css" rel="stylesheet" type="text/css" />
	<![endif]-->

    <!--[if IE 7]>
	<link href="/shop/images/img002/style/css/screen/content_eidamo_ie7.css" rel="stylesheet" type="text/css" />
	<![endif]-->

    <!--[if lte IE 6]>
	<link href="/shop/images/img002/style/css/patches/patch_3col_fullheight.css" rel="stylesheet" type="text/css" />
	<link href="/shop/images/img002/style/css/screen/content_eidamo_ie6.css" rel="stylesheet" type="text/css" />
	<![endif]-->

    <!--[if lte IE 9]>
		<link href="/shop/images/img002/main/custom_design/01_ie9.css" rel="stylesheet" type="text/css" />
		<![endif]-->

    <!--[if lte IE 8]>
		<link href="/shop/images/img002/main/custom_design/01_ie8.css" rel="stylesheet" type="text/css" />
		<![endif]-->

    <!--[if lte IE 7]>
		<link href="/shop/images/img002/main/custom_design/01_ie7.css" rel="stylesheet" type="text/css" />
		<![endif]-->

    <!--[if lte IE 6]>
		<link href="/shop/images/img002/main/custom_design/01_ie6.css" rel="stylesheet" type="text/css" />
		<![endif]-->

    <script type="text/javascript">
        if(window.location.pathname == '/'){
            document.write('<link href=' + '"{% static 'css/home.css' %}"' +  'rel="stylesheet" type="text/css">');
        } else{
            document.write('<link href=' + '"{% static 'css/content_eidamo.css' %}"' +  'rel="stylesheet" type="text/css">');
        }
    </script>

    <!-- (en) Tie-in for jQuery and the used plugins -->
    <!-- (de) Einbindung von jQuery und verwendete plugins -->

    <script type="text/javascript" src="{% static 'js/jquery.library.min.js' %}"></script>

    <!-- my js -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>

    <script src="{% static 'js/shop_0.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
        $(window).load(function() {
            $(".loader").fadeOut("slow");
        });

        $(document).on({
            ajaxStart: function() { $(".loader").fadeIn('fast'); },
            ajaxStop: function() { $(".loader").fadeOut('fast'); }
        });
    </script>

</head>

<body id="shop_main">

<div class="loader"></div>

{% block breadcrumbs %}{% endblock %}

{% block register %}

    <div class="page_margins">

        <div class="page">

            <div class="pagePadding">

                {% block cart %}

                    <div id="header" role="banner">
                        <span class="headerInner">

                            <div id="fix-head">
                                <div id="topnav" role="contentinfo">

                                    <span id="messages">

                                        {% include 'messages.html' %}

                                    </span>

                                    <span style="float: right">

                                            <!-- LOG IN / EINLOGGEN -->
                                        {% if request.user.is_authenticated %}
                                            <a class="exchange" href="{% url 'buyer:logout' %}?next={{ request.path }}" title="{{ request.user.get_full_name }}">
                                                Выйти (<b> {{ request.user.get_full_name }} </b>)
                                            </a>
                                        {% else %}

                                            <a href="{% url 'buyer:register' %}" title="Регистрация / Войти">
                                                Регистрация
                                            </a>

                                        {% endif %}

                                        <!-- MY CART / WARENKORB -->
                                            <a class="cart_url" href="{% url 'cart:detail' %}" title="Корзина">
                                                Корзина: <b>{% if total_price %}{{ total_price }}{% else %}0.00{% endif %}&nbsp;EUR*</b>
                                            </a>
                                            <a class="exchange" href="#" title="Курс">
                                                Курс EUR: <b>{{ exchange }}</b>
                                            </a>
                                        </span>

                                </div>
                            </div>

                            <h1>
                                <a href="{% url 'menu:homepage' %}" title="Sturm MIL-TEC® Online-Shop : Главная">
                                    <img src="{% static 'img/logo.png' %}" alt="Sturm MIL-TEC® Online-Shop">
                                </a>
                            </h1>
                        </span>
                    </div>

                    {% include "navbar.html" %}

                    {% block content %}


                        <div id="main"><span class="main">

            <!-- begin: #col3 static center column -->
            <div id="col3" role="main">
                <div id="col3_content" class="clearfix">
                    <img class="start_picture" src="{% static 'img/grafik_mitte.jpg' %}" alt="Sturm MIL-TEC® Online-Shop" title="Sturm MIL-TEC® Online-Shop">

                    <!-- EIDAMO_CUSTOMERLOGIN_START -->
                    <div class="boxen">
                        <div class="first box">
                            <div class="textContainer">
                                <h3>ЗАМЕТКА</h3>
                                <p>Пожалуйста, обратите внимание, что мы являемся оптовым дистрибьютором и поставки только для уполномоченных дилеров</p>
                            </div>

                            <div class="buttonsContainer">
                                <a href="#" target="_blank" title="Найти дилера" class="formButton">
                                    <b>Найти дилера</b>
                                </a>
                            </div>
                        </div>

                        <div class="last box">

                            {% if request.user.is_authenticated %}

                                <div class="textContainer">
                                    <h3>РЕГИСТРАЦИЯ В КАЧЕСТВЕ АВТОРИЗОВАННОГО ДИЛЕРА</h3>
                                    <p>Вы еще не Mil-Tec<sup>®</sup><br>специалист дилера?</p>
                                    <p>Здесь вы можете стать одним ...</p>
                                </div>

                                <div class="buttonsContainer">
                                    <a  href="{% url 'buyer:update' %}" title="Изменить профиль" class="formButton">
                                        <b>Изменить профиль</b>
                                    </a>
                                </div>

                            {% else %}

                                <div class="textContainer">
                                    <h3>РЕГИСТРАЦИЯ В КАЧЕСТВЕ АВТОРИЗОВАННОГО ДИЛЕРА</h3>
                                    <p>Вы еще не Mil-Tec<sup>®</sup><br>специалист дилера?</p>
                                    <p>Здесь вы можете стать одним ...</p>
                                </div>

                                <div class="buttonsContainer">
                                    <a  href="{% url 'buyer:register' %}" title="Регистрация" class="formButton">
                                        <b>РЕГИСТРАЦИЯ</b>
                                    </a>
                                </div>

                            {% endif %}

                        </div>

                        <div class="shop box">
                            {% if request.user.is_authenticated %}

                                <div class="textContainer">
                                    <h3>ИНТЕРНЕТ МАГАЗИН</h3>
                                    <p>Пожалуйста, обратите внимание, что мы являемся оптовым дистрибьютором и поставки только для уполномоченных дилеров</p>
                                </div>

                                <div class="buttonsContainer">
                                    <a href="{% url 'buyer:logout' %}" title="Выйти" class="formButton">
                                        <b>Выйти</b>
                                    </a>
                                </div>

                            {% else %}

                                <h3>ИНТЕРНЕТ МАГАЗИН</h3>
                                <div class="forms">

                                    {% include 'login.html' %}

                                </div>

                            {% endif %}
                        </div>
                    </div>
                </div>
                <div id="ie_clearing">&nbsp;</div>

            </div>

        </span>
                        </div>

                    {% endblock %}

                    <div class="clear"></div>

                {% endblock cart %}

            </div>

        </div>

    </div>

    {% include "footer.html" %}

{% endblock %}

<!-- (en) Workaround for IE8 und Webkit browsers to fix focus problems when using skiplinks -->
<!-- (de) Workaround für IE8 und Webkit browser, um den Focus zu korrigieren, bei Verwendung von Skiplinks -->

<script src="{% static 'js/my_js.js' %}" type="text/javascript"></script>
<script src="{% static 'js/product.js' %}" type="text/javascript"></script>
<script src="{% static 'js/buyer.js' %}" type="text/javascript"></script>

{% block script %}{% endblock %}

</body>
</html>

templates/footer.html
{% load staticfiles %}

<div id="footer" role="contentinfo">
    <div id="footer_content">

        <div class="c16l">
            <ul>
                <li><a href="#">Главная</a></li>
                <li><a href="#">Поиск деталей</a></li>
                <li><a href="#">Вернуться к началу</a></li>

            </ul>
        </div>

        <div class="c16l">
            <ul>
                <li>
                    <a href="#" title="Контакт" target="_blank">Контакт</a>
                </li>
                <li>
                    <a href="#" target="_blank">Форма возврата</a>
                </li>
            </ul>
        </div>

        <div class="c16l">
            <ul>
                <li>
                    <a href="#">Выходные данные</a>
                </li>

                <li>
                    <a href="#">Защита & Условия</a>
                </li>

                <li>
                    <a href="#">Правила и условия продажи</a>
                </li>

            </ul>
        </div>

    </div>

    <div class="footerCopyrights">

        <div class="float_left">

            * Цены без учета. налоговые и транспортные сборы, если не указано иное.

            <br>

            <!--[*EIDAMO_WORDS:COPYRIGHT_DATE*]-->© 2004-2015 Sturm Handels GmbH Все права защищены.
        </div>

    </div>

    <div class="edge edge-bl"></div>
    <div class="edge edge-br"></div>
</div>
<!-- end: #footer -->

templates/messages.html
{% if messages %}
        {% for message in messages%}
            <div class="messages has-{{ message.extra_tags }}">
                <label class="control-label">
                    <p><em>{{ message }}</em></p>
                </label>
            </div>
        {% endfor %}
{% endif %}

templates/navbar.html
{% load staticfiles %}

<div id="nav" role="navigation">
     <span class="navInner">

	  <div class="hlist">
          <ul>
              <!-- PRODUCTS / PRODUKTE -->
              <li id="id_nav_top_products" style="background-color:#961400;" class="first">
                  <a href="{% url 'menu:shop' %}" title="МАГАЗИН">
                      <span style="color:#fff;">
                          <img src="{% static 'img/icon_shop.gif' %}">
                          МАГАЗИН
                      </span>
                  </a>
              </li>

              <!-- STARTPAGE / STARTSEITE -->
              <li id="id_nav_top_startseite">
                  <a href="{% url 'menu:homepage' %}" title="ГЛАВНАЯ">
                      <span>
                          ГЛАВНАЯ
                      </span>
                  </a>
              </li>

              <!-- ABOUT US / ÜBER UNS -->

              <li id="id_nav_top_darstellung" cla>
                  <a href="#" title="КОМПАНИЯ" target="_blank">
                      <span>
                          КОМПАНИЯ
                      </span>
                  </a>
              </li>

              <!-- CONTACT / KONTAKT -->
              <li id="id_nav_top_contact">
                  <a href="#" title="КОНТАКТЫ" target="_blank">
                      <span>
                          КОНТАКТЫ
                      </span>
                  </a>
              </li>

          </ul>
      </div>

         {% if request.path != "/" %}

             <form method="get" class="searchForm" id="searchForm" action="{% url 'product:search' %}" >

                 <div class="searchInput">
                <span>
              <img src="{% static 'img/gfx.spacer.gif' %}" class="icon icon-lg-search">

              <input id="query" class="searchInput" value="{{ request.GET.q }}" type="text" name="q"  placeholder="Искать ...">

              <input class="searchButton" type="image" border="0" name="submit" title="Поиск" alt="Поиск" src="{% static 'img/gfx.spacer.gif' %}">

            </span>
                 </div>

             </form>

         {% endif %}

    </span>
</div>